apiVersion: apps/v1
kind: Deployment
metadata:
  name: demostore
  namespace: demostore
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: demostore
  template:
    metadata:
      labels:
        app: demostore
    spec:
      containers:
        - name: demostore
          image: eu.gcr.io/production-243513/demostore:master
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: |
                -XX:+PrintCommandLineFlags
                -XX:+UnlockExperimentalVMOptions
                -XX:+EnableJVMCI
                -XX:+UseJVMCICompiler
                -Dgraal.GraalArithmeticStubs=false
            - name: SERVER_PORT
              value: "8080"
          resources:
            requests:
              memory: 300Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /
